config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
  resources :graphs do
    resources :trackables do
      resources :points
    end
  end

  resources :trackables, only: [:destroy]

  root 'graphs#index'
end

app/models/graph.rb
class Graph < ActiveRecord::Base
  belongs_to :user
  has_many :trackables

  validates :name, presence: true 
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :trackable
  validates :value, presence: true
end

app/models/trackable.rb
class Trackable < ActiveRecord::Base
  belongs_to :graph
  has_many :points

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :graphs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController

  before_action :authenticate_user!

  def index
    @graphs = current_user.graphs.all.order('updated_at DESC')
  end

  def show
    @graph = Graph.find(params[:id])
    @trackables = @graph.trackables.all
    @trackables.each do |trackable|
      points = trackable.points.all
      points.each do |point|
        @y_max == nil || point.value > @y_max ? @y_max = point.value : @y_max = @y_max #seems redundant to assign to itself
        @y_min == nil || point.value < @y_min ? @y_min = point.value : @y_min = @y_min
      end
    end
  end

  def new
    @graph = current_user.graphs.build
  end

  def create
    @graph = current_user.graphs.build(graph_params)
    if @graph.save
      redirect_to @graph
    else
      render 'new'
    end
  end

  def destroy
    Graph.find(params[:id]).destroy
    flash[:success] = "Graph deleted"
    redirect_to root_url
  end

private
  
  def graph_params
    params.require(:graph).permit(:name)
  end


end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  
def create
  @trackable = Trackable.find(params[:trackable_id])
  @point = @trackable.points.build(params.require(:point).permit(:value))
  if @point.save
    redirect_to @trackable.graph 
    # Success message here
  else
    redirect_to @trackable.graph #possibly dry this
    # Failure message here
  end
end

end

app/controllers/trackables_controller.rb
class TrackablesController < ApplicationController
  
  def create
    @graph = Graph.find(params[:graph_id])
    @trackables = @graph.trackables.create(params[:trackable].permit(:name, :kind, :min, :max))

    if @trackables.save
      redirect_to @graph
      # Success message
    else 
      redirect_to @graph
      # Failure message
    end
  end

  def destroy
    @trackable = Trackable.find(params[:id])
    @graph=@trackable.graph
    @trackable.destroy
    redirect_to @graph
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def times_2(number)
    puts number*2
  end

end

app/helpers/graphs_helper.rb
module GraphsHelper
  def times_2(number)
    puts number*2
  end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/trackables_helper.rb
module TrackablesHelper
end

app/views/graphs/_chart.html.erb
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

<script type="text/javascript">
  $(function () {
    $('#container').highcharts({

        exporting: { enabled: false 
        },

          credits: {
            enabled: false
        },

        chart: {
            type: 'spline'
        },
        title: {
            text: false
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: { // don't display the dummy year
                month: '%e. %b',
                year: '%b'
            },
            title: {
                text: 'Date'
            }
        },
        yAxis: {

            labels: {
                enabled: true
            },

            title: {
                text: ''
            },
            min: <%= @y_min %>,
            max: <%= @y_max %>,

        }, 

        tooltip: {
            headerFormat: '<b>{series.name}</b><br>',
            pointFormat: '{point.x:%e. %b}'
            //: {point.y:.2f} m'
        },

        plotOptions: {
            spline: {
                marker: {
                    enabled: true
                }
            }
        },



        series: 
        [
        <% @trackables.each do |trackable| %> 
            {
            name: "<%= trackable.name %>",
        <% @trackable_data = [] %>
        <% trackable.points.each do |point| %>
            
            <% @trackable_data << [point.created_at.to_i*1000, point.value] %>
        <% end %>
            data: <%= @trackable_data %> 
            },
        <% end %>
        ] 
    });
});
</script>

app/views/graphs/_form.html.haml
= simple_form_for @graph do |f|
  

  = f.input :name, input_html: { class: 'form-control'}
  = f.button :submit, class: "btn btn-primary"

app/views/graphs/_graph.html.haml
%li
  = link_to graph.name, graph, class: "graphs-list"
  = link_to "delete", graph, method: :delete, data: { confirm: "Delete graph and all it's data?"}

app/views/graphs/index.html.haml
= render @graphs # renders _graph partial and passes in each graph

app/views/graphs/new.html.haml
%h1 New Graph

= render 'form'

//= render 'trackable_form'

app/views/graphs/show.html.haml
%h1= @graph.name
%br

- if @graph.trackables.any?
  = render 'chart'

  = render 'points/form'
    

  %br
  %br

%h3 Add New Trackable
= render 'trackables/form'

%br
%br
%br
= link_to "Delete Graph", @graph, method: :delete, data: { confirm: "Delete graph and trackables?"}, class: "btn btn-default" 

app/views/layouts/_header.html.haml
.navbar.navbar-default
  .container-fluid
    = link_to "Graphs", graphs_path, id: "logo"
    .new-graph
      = link_to "New Graph", new_graph_path

app/views/layouts/_script_links.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>



<!--<script src="https://code.highcharts.com/highcharts.js"></script>-->
<script src="https://code.highcharts.com/modules/exporting.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1"}
    %title Graphit
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    / Likely more efficient way to implement JS with Rails
    = render 'layouts/script_links'


  %body
    = render 'layouts/header'
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert, alert-#{name}"
      = yield

app/views/points/_form.html.haml
- @trackables.each do |trackable|
  = simple_form_for([@graph, trackable, trackable.points.build]) do |f|
    
    = f.input :value, label: trackable.name, input_html: { class: "form-control" }
    = f.button :submit, class: "btn btn-default"  
    = link_to "Delete Trackable", trackable_path(trackable), method: :delete, data: { confirm: "Delete trackable?"}, class: "btn btn-default", id: "delete-trackable-btn" 

app/views/trackables/_form.html.haml
= simple_form_for([@graph, @graph.trackables.build]) do |f|
  
  = f.input :name, input_html: { class: "form-control" }
  = f.button :submit, class: "btn btn-default"  